### ISSUE TITLE
Edit issue template for 'talks' repo to add "Previous talks experience" 

### ISSUE THREAD

**Issue by iayanpahwa** [ILUGD/volunteers-tasks#1]
Created on : 7th April 2020
------------------------------------------
Add section allowing anyone opening an issue for talk to add previous speaking experience

**Comment by hellozee** [comment]
Done, :3

**Comment by iayanpahwa** [comment]
The idea was to work on issues and keep it open to be closed during the volunteer call, so re-opening again for now !!

**Comment by miphilomath** [comment]
Since this task is done, closing the issue.
