### ISSUE TITLE
Add call for collaboration for online events

### ISSUE THREAD

**Issue by iayanpahwa** [ILUGD/volunteers-tasks#3]
- Website
- Telegram
- Mailing List
- twitter
- meetup events

**Comment by iayanpahwa** [comment]
Text
====================================

Call for collaboration:

If you are a speaker, community or a meet-up group and wants to collaborate with ILUG-D
( https://twitter.com/ilugdelhi ) and HHC-D ( https://twitter.com/DelhiHHC ) for upcoming online sessions, please tweet us or comment on our meet-up events - https://www.meetup.com/ilugdelhi/

If you're interesting in giving a talk, please feel free to propose by creating an issue here --> https://github.com/ILUGD/talks/issues

====================================

@xeon-zolt , @miphilomath, @alok760 please tweet this and add this to all meet-up events description.

**Comment by tm9k1** [comment]
I don't see why was this issue closed, @iayanpahwa ?

**Comment by iayanpahwa** [comment]
> I don't see why was this issue closed, @iayanpahwa ?

I felt like closing it so I did.

**Comment by tm9k1** [comment]
I think this was discussed with the volunteers in the community call and we had a positive heading with it? Was closing this issue discussed any time later?

> > I don't see why was this issue closed, @iayanpahwa ?
> 
> I felt like closing it so I did.

Also, this sounds irresponsible to me as a fellow volunteer. IMHO, Call for collaborations has a lot of potential to boost the outreach of ILUGD. I believe this should have been discussed in much more detail in the group before dropping the idea completely.

**Comment by tm9k1** [comment]
let's discuss this issue in the next community call and close it then, given that we have a valid reason not to pursue this idea. :-)

**Comment by iayanpahwa** [comment]
> let's discuss this issue in the next community call and close it then, given that we have a valid reason not to pursue this idea. :-)

I don’t answer to you, especially when you have no background of the things you’re talking about. Also I can close the issues I opened. Hope that clears

**Comment by tm9k1** [comment]
for someone who would like to check the conversation here, I'm posting the screenshots of the apparently one-sided conversation. Have a look:-
![image](https://user-images.githubusercontent.com/22996531/80311333-b7009b00-87fc-11ea-9d46-0d788c6f9b4c.png)

![image](https://user-images.githubusercontent.com/22996531/80311340-c08a0300-87fc-11ea-8edf-4eef9a3009d7.png)

![image](https://user-images.githubusercontent.com/22996531/80311342-ca136b00-87fc-11ea-9f41-a53214746cff.png)

**Comment by iayanpahwa** [comment]
@taskmaster9001 for someone willing to check the conversation, they can simply do it by going thru the comments above. Let’s not generate unnecessary carbon footprints by uploading heavy screenshots of redundant conversation and have mercy on this planet, hope that makes sense. Thank you!
