### ISSUE TITLE
add upcoming meet-ups on meetup.org

### ISSUE THREAD

**Issue by iayanpahwa** [ILUGD/volunteers-tasks#4]
for next two weeks

**Comment by hellozee** [comment]
Talking about meetup.com, I think it has been more of a burden then something that would have been helpful. I would rather suggest a better workflow to handle the scheduling the events and reaching out to the public.

Using calendars is a good idea, that way we could automate the sending mails to the mailing list about the upcoming events. But that would first require to fix the issues with mailing lists first.

**Comment by xeon-zolt** [comment]
but it helped others in reaching us mostly for first-timers I reached group from meetups, also true ki its not easy Kuki Abhi meetups ki frequency Kafi Jada h

**Comment by hellozee** [comment]
Thats a good point. That also raises the question on having dedicated people for doing the social media stuff. Ideally they have to be automated but for now, we need at least 1 dedicated person to manage each social media. And by social media I mean FaceBook, XD

**Comment by xeon-zolt** [comment]
like for youtube it's me and mason sometime I am not available sometimes I am not so 2-3 should be there and they can divide among themselves

**Comment by tm9k1** [comment]
https://www.meetup.com/ilugdelhi/events/

I don't see any meetup lined for the coming two sets of weekends. Did we discuss this on the group yet?

**Comment by iayanpahwa** [comment]
@alok760 calendar for next 2 weeks is ready, let's schedule on meetup.org and please also add the section on how to give a talk at ILUG-D
