### ISSUE TITLE
Add GitHub integration bot to telegram channel

### ISSUE THREAD

**Issue by iayanpahwa** [ILUGD/volunteers-tasks#6]

**Comment by hellozee** [comment]
Wasn't it already there?

**Comment by hellozee** [comment]
Ah, it was removed cause a lot of people were triggering it by mistake and it was making the channel noisy.

**Comment by xeon-zolt** [comment]
we want a solution were it post a list of open issues in the group for volunteer tasks

**Comment by iayanpahwa** [comment]
Since we are having regular meetings and there is a minimal working bot, closing this issue for now.
